use_frameworks!

target 'CascadingTableDelegate_Example' do
  pod 'CascadingTableDelegate', :path => '../'

  target 'CascadingTableDelegate_Tests' do
    inherit! :search_paths

    pod 'Quick', '0.10.0'
    pod 'Nimble', '5.1.1'
  end
end
