use_frameworks!

target 'CascadingTableDelegate_Example' do
  pod 'CascadingTableDelegate', :path => '../'

  target 'CascadingTableDelegate_Tests' do
    inherit! :search_paths

    pod 'Quick', "1.2.0"
    pod 'Nimble', "7.0.2"
  end
end
